
CREATE TABLE IF NOT EXISTS http_sessions (
	key NAME NOT NULL,
	data BYTEA NOT NULL,
	created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMPTZ,
	expires_on TIMESTAMPTZ NOT NULL,
	PRIMARY KEY (key)
);
