// Code generated by "stringer -type=ErrorCode -trimprefix=ErrorCode -output errors_string.go"; DO NOT EDIT.

package i18n

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrOK-0]
	_ = x[ErrSystemError-1]
	_ = x[ErrSystemFailed-2]
	_ = x[ErrSystemPause-3]
	_ = x[ErrSystemReadonly-4]
	_ = x[ErrNotFound-8]
	_ = x[ErrForbiddedn-9]
	_ = x[ErrParamRequired-10]
	_ = x[ErrParamInvalid-11]
	_ = x[ErrLoginFailed-15]
	_ = x[ErrAuthRequired-16]
	_ = x[ErrVerifySend-17]
	_ = x[ErrRegistFaild-18]
	_ = x[ErrNoneMobile-19]
	_ = x[ErrBadAlias-20]
	_ = x[ErrBadEmail-21]
	_ = x[ErrBadMobile-22]
	_ = x[ErrAliasTaken-23]
	_ = x[ErrMobileTaken-24]
	_ = x[ErrBadVerifyCode-25]
	_ = x[ErrTokenExpired-26]
	_ = x[ErrTokenInvalid-27]
	_ = x[ErrOldPassword-28]
	_ = x[ErrEmptyPassword-29]
	_ = x[ErrSimplePassword-30]
	_ = x[ErrMultiOnline-31]
	_ = x[ErrEqualOldMobile-32]
	_ = x[ErrAliasTooFew-33]
	_ = x[ErrEnableTwoFactor-37]
	_ = x[ErrTwoFactorCode-38]
	_ = x[ErrSNSInfoLost-42]
	_ = x[ErrSNSBindFailed-43]
}

const (
	_ErrorCode_name_0 = "ErrOKErrSystemErrorErrSystemFailedErrSystemPauseErrSystemReadonly"
	_ErrorCode_name_1 = "ErrNotFoundErrForbiddednErrParamRequiredErrParamInvalid"
	_ErrorCode_name_2 = "ErrLoginFailedErrAuthRequiredErrVerifySendErrRegistFaildErrNoneMobileErrBadAliasErrBadEmailErrBadMobileErrAliasTakenErrMobileTakenErrBadVerifyCodeErrTokenExpiredErrTokenInvalidErrOldPasswordErrEmptyPasswordErrSimplePasswordErrMultiOnlineErrEqualOldMobileErrAliasTooFew"
	_ErrorCode_name_3 = "ErrEnableTwoFactorErrTwoFactorCode"
	_ErrorCode_name_4 = "ErrSNSInfoLostErrSNSBindFailed"
)

var (
	_ErrorCode_index_0 = [...]uint8{0, 5, 19, 34, 48, 65}
	_ErrorCode_index_1 = [...]uint8{0, 11, 24, 40, 55}
	_ErrorCode_index_2 = [...]uint16{0, 14, 29, 42, 56, 69, 80, 91, 103, 116, 130, 146, 161, 176, 190, 206, 223, 237, 254, 268}
	_ErrorCode_index_3 = [...]uint8{0, 18, 34}
	_ErrorCode_index_4 = [...]uint8{0, 14, 30}
)

func (i ErrorCode) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _ErrorCode_name_0[_ErrorCode_index_0[i]:_ErrorCode_index_0[i+1]]
	case 8 <= i && i <= 11:
		i -= 8
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	case 15 <= i && i <= 33:
		i -= 15
		return _ErrorCode_name_2[_ErrorCode_index_2[i]:_ErrorCode_index_2[i+1]]
	case 37 <= i && i <= 38:
		i -= 37
		return _ErrorCode_name_3[_ErrorCode_index_3[i]:_ErrorCode_index_3[i+1]]
	case 42 <= i && i <= 43:
		i -= 42
		return _ErrorCode_name_4[_ErrorCode_index_4[i]:_ErrorCode_index_4[i+1]]
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
