// Code generated by "stringer -type=ErrorValue -trimprefix=ErrorValue -output errors_string.go"; DO NOT EDIT.

package i18n

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrOK-0]
	_ = x[ErrSystemError-1]
	_ = x[ErrSystemFailed-2]
	_ = x[ErrSystemPause-3]
	_ = x[ErrSystemReadonly-4]
	_ = x[ErrNotFound-6]
	_ = x[ErrForbiddedn-7]
	_ = x[ErrParamRequired-8]
	_ = x[ErrParamInvalid-9]
	_ = x[ErrLoginFailed-11]
	_ = x[ErrAuthRequired-12]
	_ = x[ErrVerifySend-13]
	_ = x[ErrRegistFaild-14]
	_ = x[ErrNoneMobile-15]
	_ = x[ErrBadAlias-16]
	_ = x[ErrBadEmail-17]
	_ = x[ErrBadMobile-18]
	_ = x[ErrAliasTaken-19]
	_ = x[ErrMobileTaken-20]
	_ = x[ErrBadVerifyCode-21]
	_ = x[ErrTokenExpired-22]
	_ = x[ErrTokenInvalid-23]
	_ = x[ErrOldPassword-24]
	_ = x[ErrEmptyPassword-25]
	_ = x[ErrSimplePassword-26]
	_ = x[ErrMultiOnline-27]
	_ = x[ErrEqualOldMobile-28]
	_ = x[ErrAliasTooFew-29]
	_ = x[ErrEnableTwoFactor-31]
	_ = x[ErrTwoFactorCode-32]
	_ = x[ErrSNSInfoLost-34]
	_ = x[ErrSNSBindFailed-35]
}

const (
	_ErrorValue_name_0 = "ErrOKErrSystemErrorErrSystemFailedErrSystemPauseErrSystemReadonly"
	_ErrorValue_name_1 = "ErrNotFoundErrForbiddednErrParamRequiredErrParamInvalid"
	_ErrorValue_name_2 = "ErrLoginFailedErrAuthRequiredErrVerifySendErrRegistFaildErrNoneMobileErrBadAliasErrBadEmailErrBadMobileErrAliasTakenErrMobileTakenErrBadVerifyCodeErrTokenExpiredErrTokenInvalidErrOldPasswordErrEmptyPasswordErrSimplePasswordErrMultiOnlineErrEqualOldMobileErrAliasTooFew"
	_ErrorValue_name_3 = "ErrEnableTwoFactorErrTwoFactorCode"
	_ErrorValue_name_4 = "ErrSNSInfoLostErrSNSBindFailed"
)

var (
	_ErrorValue_index_0 = [...]uint8{0, 5, 19, 34, 48, 65}
	_ErrorValue_index_1 = [...]uint8{0, 11, 24, 40, 55}
	_ErrorValue_index_2 = [...]uint16{0, 14, 29, 42, 56, 69, 80, 91, 103, 116, 130, 146, 161, 176, 190, 206, 223, 237, 254, 268}
	_ErrorValue_index_3 = [...]uint8{0, 18, 34}
	_ErrorValue_index_4 = [...]uint8{0, 14, 30}
)

func (i ErrorValue) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _ErrorValue_name_0[_ErrorValue_index_0[i]:_ErrorValue_index_0[i+1]]
	case 6 <= i && i <= 9:
		i -= 6
		return _ErrorValue_name_1[_ErrorValue_index_1[i]:_ErrorValue_index_1[i+1]]
	case 11 <= i && i <= 29:
		i -= 11
		return _ErrorValue_name_2[_ErrorValue_index_2[i]:_ErrorValue_index_2[i+1]]
	case 31 <= i && i <= 32:
		i -= 31
		return _ErrorValue_name_3[_ErrorValue_index_3[i]:_ErrorValue_index_3[i+1]]
	case 34 <= i && i <= 35:
		i -= 34
		return _ErrorValue_name_4[_ErrorValue_index_4[i]:_ErrorValue_index_4[i+1]]
	default:
		return "ErrorValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
