name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
      - feat*
  pull_request:

  check:
    name: Vet & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run go vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: "goinstall"
          version: v1.64
